
# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add Auth0 environment variables placeholder
[template.environment]
  VITE_AUTH0_DOMAIN = "Your Auth0 Domain"
  VITE_AUTH0_CLIENT_ID = "Your Auth0 Client ID"
