// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shbkrbtcnfkvjzzpddkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoYmtyYnRjbmZrdmp6enBkZGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MDQ3MDIsImV4cCI6MjA2MTQ4MDcwMn0.gpm0oMeFlNH2W7JrbEi42fqehselOtF9H2RllHESdZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);