// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqkbmqsteaszilwamqic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxa2JtcXN0ZWFzemlsd2FtcWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDIzNjMsImV4cCI6MjA2MTU3ODM2M30.tg6D6yGydN4PjqM8N9rWC78G0m9DaF8726opRbxeKPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);